// <auto-generated />
using CafeDine.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CafeDine.Migrations
{
    [DbContext(typeof(DineContext))]
    partial class DineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CafeDine.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Paragraph")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new { Id = 1, Logo = " <i class='icofont-soup-bowl'></i>", Paragraph = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia animi ipsam obcaecati.</p>", Title = "<h3 class='mt-3'>Delicious Food</h3>" },
                        new { Id = 2, Logo = " <i class='icofont-tasks'></i>", Paragraph = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia animi ipsam obcaecati.</p>", Title = "<h3class='mt-3'>Online Order</h3>" },
                        new { Id = 3, Logo = "<i class='icofont-map-pins'></i>", Paragraph = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia animi ipsam obcaecati.</p>", Title = "<h3 class='mt-3'>Free delivery</h3>" }
                    );
                });

            modelBuilder.Entity("CafeDine.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Button")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Paragraph")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new { Id = 1, Button = "<a class='btn btn-main mr-3' data-swiper-parallax='500'>View Menu</a>", Image = "pizza.jpg", Paragraph = " <h1 class='text-white'>Fresh,Delicious meal to reach your optimum health and fitness</h1>", Title = " <span class='text-white'> Welcome to restuarant</span> " },
                        new { Id = 2, Button = "<a class='btn btn-main mr-3' data-swiper-parallax='500'>View Menu</a>", Image = "pizza2.jpg", Paragraph = "<h1 class='text-white'>Good food starts with good ingridients.Have a great time with us</h1>", Title = " <span class='text-white'>Welcome to restuarant</span> " },
                        new { Id = 3, Button = "<a class='btn btn-main mr-3' data-swiper-parallax='500'>View Menu</a>", Image = "pizza3.jpg", Paragraph = "<h1 class='text-white'>We deliver good quality food with great service to our customers</h1>", Title = " <span class='text-white'>Welcome to restuarant</span> " }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
